Bump version again to fix PyPI uploading issue
I derped uploading the sdist.

``````
running upload
Submitting dist/teamsupport-0.1.1.tar.gz to https://pypi.python.org/pypi
Upload failed (400): This filename has previously been used, you should
use a different version.
error: Upload failed (400): This filename has previously been used, you
should use a different version.
```